# Converted from: track.ipynb
# Generated by convert_notebooks.py
# Date: 2026-05-22 20:27:11

# --- Cell 1 ---
from yolo_deepsort import main
track = main()
track()

# --- Cell 2 ---


# --- Cell 3 ---


# --- Cell 4 ---


# --- Cell 5 ---

